version: 0.2

phases:
  install:
    commands:
      - export AWS_DEFAULT_REGION=us-east-1
      - sudo apt-get update
      #- sudo apt install python3.9 -y
      - python --version
      - pip install -U setuptools
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - pip install aws-sam-cli
      
  
  build:
    commands:
      - sam --version
      - aws --version
      - echo $S3_BUCKET
      - env
      - sam build --template function_template.yml -b build/lambda-function
      - sam package --template-file build/lambda-function/template.yml --s3-bucket $S3_BUCKET --output-template-file lambda.yml

artifacts:
  secondary-artifacts:
    secondary_artifact_packaged:
      files:
        - lambda.yml
      discard-paths: yes
  
